#!/usr/bin/env bash

{
  echo -e 'Input{mergeCommits=[\n""'
  git log --all --merges --pretty=format:',"%H"'
  echo -e '\n],\ncommits=[\nCommit{commitHash="",authorName="",authorEmail="",authorDate="",committerName="",committerEmail="",committerDate="",subject=""}'
  git log --all --pretty=format:',Commit{commitHash="%H",authorName="%an",authorEmail="%ae",authorDate="%aI",committerName="%cn",committerEmail="%ce",committerDate="%cI",subject="%f"}'
  echo -e '\n]}'
} > "$TMPDIR/.git-cvc.txt"
REPOSITORY=$(git remote -v | grep '^origin' | grep '(fetch)$' | awk '{print $2}' | awk -F'/' '{print $NF}' | awk -F'.' '{print $1}') git-contribution-visualizer listCommits < "$TMPDIR/.git-cvc.txt"
rm "$TMPDIR/.git-cvc.txt"
