#!/usr/bin/env bash

git log --pretty=format:'Commit{commitHash="%H",authorName="%an",authorEmail="%ae",authorDate="%aI",committerName="%cn",committerEmail="%ce",committerDate="%cI",subject="%f"}' | REPOSITORY=$(git remote -v | grep '^origin' | grep '(fetch)$' | awk '{print $2}' | awk -F'/' '{print $NF}' | awk -F'.' '{print $1}') git-contribution-visualizer listCommits
